# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pymodaq5_debug\pulse_extension\fit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pymodaq_plugins_pulsedmeasurement.resources import fit_methods as fit


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(475, 375)
        self.Form = Form
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fit_comboBox = QtWidgets.QComboBox(Form)
        self.horizontalLayout.addWidget(self.fit_comboBox)
        for model in [
            name
            for name in dir(fit)
            if name.endswith("_model") and not name.startswith("_")
        ]:
            self.fit_comboBox.addItem(" ".join(model.split("_")[:-1]))
        self.fit_comboBox.currentTextChanged.connect(self.add_remove_sinbox)
        spacerItem = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.sb_state = False
        self.add_remove_sinbox()
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

    def add_remove_sinbox(self):
        if "multi" in self.fit_comboBox.currentText() and self.sb_state == False:
            self.N_spinBox = QtWidgets.QSpinBox(self.Form)
            self.horizontalLayout.addWidget(self.N_spinBox)
            self.sb_state = True
        elif not "multi" in self.fit_comboBox.currentText() and self.sb_state == True:
            self.N_spinBox.deleteLater()
            self.sb_state = False


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
