# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pulse_programmer - Copie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import inspect
import sys

sys.path.append(r"C:\Users\Aurore")
import pymodaq_pulse_sequences
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    selected_sequence: str = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 672)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_settings = QtWidgets.QHBoxLayout()
        self.layout_settings.setObjectName("layout_settings")
        self.layout_channel = QtWidgets.QVBoxLayout()
        self.layout_channel.setObjectName("layout_channel")
        self.label_channels = QtWidgets.QLabel(self.centralwidget)
        self.label_channels.setObjectName("label_channels")
        self.layout_channel.addWidget(self.label_channels)
        self.layout_channel_2 = QtWidgets.QHBoxLayout()
        self.layout_channel_2.setObjectName("layout_channel_2")
        self.layout_channel_MW = QtWidgets.QVBoxLayout()
        self.layout_channel_MW.setObjectName("layout_channel_MW")
        self.param_channel_MW = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_MW.setObjectName("param_channel_MW")
        self.layout_channel_MW.addWidget(self.param_channel_MW)
        self.label_channel_MW = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_MW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_MW.setObjectName("label_channel_MW")
        self.layout_channel_MW.addWidget(self.label_channel_MW)
        self.layout_channel_2.addLayout(self.layout_channel_MW)
        self.layout_channel_laser = QtWidgets.QVBoxLayout()
        self.layout_channel_laser.setObjectName("layout_channel_laser")
        self.param_channel_laser = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_laser.setObjectName("param_channel_laser")
        self.layout_channel_laser.addWidget(self.param_channel_laser)
        self.label_channel_laser = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_laser.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_laser.setObjectName("label_channel_laser")
        self.layout_channel_laser.addWidget(self.label_channel_laser)
        self.layout_channel_2.addLayout(self.layout_channel_laser)
        self.layout_channel_counter = QtWidgets.QVBoxLayout()
        self.layout_channel_counter.setObjectName("layout_channel_counter")
        self.param_channel_counter = QtWidgets.QSpinBox(self.centralwidget)
        self.param_channel_counter.setObjectName("param_channel_counter")
        self.layout_channel_counter.addWidget(self.param_channel_counter)
        self.label_channel_counter = QtWidgets.QLabel(self.centralwidget)
        self.label_channel_counter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_counter.setObjectName("label_channel_counter")
        self.layout_channel_counter.addWidget(self.label_channel_counter)
        self.layout_channel_2.addLayout(self.layout_channel_counter)
        self.layout_channel.addLayout(self.layout_channel_2)
        self.layout_settings.addLayout(self.layout_channel)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_settings.addItem(spacerItem)
        self.layout_general = QtWidgets.QVBoxLayout()
        self.layout_general.setObjectName("layout_general")
        self.label_general = QtWidgets.QLabel(self.centralwidget)
        self.label_general.setObjectName("label_general")
        self.layout_general.addWidget(self.label_general)
        self.layout_general_2 = QtWidgets.QHBoxLayout()
        self.layout_general_2.setObjectName("layout_general_2")
        self.layout_general_MWamp = QtWidgets.QVBoxLayout()
        self.layout_general_MWamp.setObjectName("layout_general_MWamp")
        self.param_general_MWamp = ScientificSpinBox(self.centralwidget)
        self.param_general_MWamp.setObjectName("param_general_MWamp")
        self.layout_general_MWamp.addWidget(self.param_general_MWamp)
        self.label_general_MWamp = QtWidgets.QLabel(self.centralwidget)
        self.label_general_MWamp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_MWamp.setObjectName("label_general_MWamp")
        self.layout_general_MWamp.addWidget(self.label_general_MWamp)
        self.layout_general_2.addLayout(self.layout_general_MWamp)
        self.layout_general_AOMdelay = QtWidgets.QVBoxLayout()
        self.layout_general_AOMdelay.setObjectName("layout_general_AOMdelay")
        self.param_general_AOMdelay = ScientificSpinBox(self.centralwidget)
        self.param_general_AOMdelay.setObjectName("param_general_AOMdelay")
        self.layout_general_AOMdelay.addWidget(self.param_general_AOMdelay)
        self.label_general_AOMdelay = QtWidgets.QLabel(self.centralwidget)
        self.label_general_AOMdelay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_AOMdelay.setObjectName("label_general_AOMdelay")
        self.layout_general_AOMdelay.addWidget(self.label_general_AOMdelay)
        self.layout_general_2.addLayout(self.layout_general_AOMdelay)
        self.layout_general_param_wait = QtWidgets.QVBoxLayout()
        self.layout_general_param_wait.setObjectName("layout_general_param_wait")
        self.param_general_wait = ScientificSpinBox(self.centralwidget)
        self.param_general_wait.setObjectName("param_general_wait")
        self.layout_general_param_wait.addWidget(self.param_general_wait)
        self.label_general_wait = QtWidgets.QLabel(self.centralwidget)
        self.label_general_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_wait.setObjectName("label_general_wait")
        self.layout_general_param_wait.addWidget(self.label_general_wait)
        self.layout_general_2.addLayout(self.layout_general_param_wait)
        self.layout_general_bin = QtWidgets.QVBoxLayout()
        self.layout_general_bin.setObjectName("layout_general_bin")
        self.param_general_bin = QtWidgets.QComboBox(self.centralwidget)
        self.param_general_bin.setObjectName("param_general_bin")
        self.layout_general_bin.addWidget(self.param_general_bin)
        self.label_general_bin = QtWidgets.QLabel(self.centralwidget)
        self.label_general_bin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_general_bin.setObjectName("label_general_bin")
        self.layout_general_bin.addWidget(self.label_general_bin)
        self.layout_general_2.addLayout(self.layout_general_bin)
        self.layout_general.addLayout(self.layout_general_2)
        self.layout_settings.addLayout(self.layout_general)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_settings.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_settings)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_parameters = QtWidgets.QWidget()
        self.tab_parameters.setObjectName("tab_parameters")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_parameters)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_add_sequence = QtWidgets.QHBoxLayout()
        self.layout_add_sequence.setObjectName("layout_add_sequence")
        self.comboBox_list_sequence = QtWidgets.QComboBox(self.tab_parameters)
        self.comboBox_list_sequence.setObjectName("comboBox_list_sequence")
        for seq in pymodaq_pulse_sequences.__all__:
            seq = "_".join(map(str, seq.split("_")[1:]))
            self.comboBox_list_sequence.addItem(seq)
        self.layout_add_sequence.addWidget(self.comboBox_list_sequence)
        self.button_add_sequence = QtWidgets.QPushButton(self.tab_parameters)
        self.button_add_sequence.setObjectName("button_add_sequence")
        self.button_add_sequence.clicked.connect(
            lambda: self.add_sequence(self.comboBox_list_sequence.currentText())
        )
        self.layout_add_sequence.addWidget(self.button_add_sequence)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_add_sequence.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.layout_add_sequence)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_T1_name = QtWidgets.QLabel(self.tab_parameters)
        self.label_T1_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T1_name.setObjectName("label_T1_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label_T1_name
        )
        self.layout_T1 = QtWidgets.QHBoxLayout()
        self.layout_T1.setObjectName("layout_T1")
        self.layout_T1_select = QtWidgets.QVBoxLayout()
        self.layout_T1_select.setObjectName("layout_T1_select")
        self.button_T1_select = QtWidgets.QPushButton(self.tab_parameters)
        self.button_T1_select.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_T1_select.setObjectName("button_T1_select")
        self.layout_T1_select.addWidget(self.button_T1_select)
        self.button_T1_remove = QtWidgets.QPushButton(self.tab_parameters)
        self.button_T1_remove.setObjectName("button_T1_remove")
        self.layout_T1_select.addWidget(self.button_T1_remove)
        self.layout_T1.addLayout(self.layout_T1_select)
        self.layout_T1_start = QtWidgets.QVBoxLayout()
        self.layout_T1_start.setObjectName("layout_T1_start")
        self.param_T1_start = ScientificSpinBox(self.tab_parameters)
        self.param_T1_start.setMinimumSize(QtCore.QSize(80, 0))
        self.param_T1_start.setMaximum(100.0)
        self.param_T1_start.setObjectName("param_T1_start")
        self.layout_T1_start.addWidget(self.param_T1_start)
        self.label_T1_start = QtWidgets.QLabel(self.tab_parameters)
        self.label_T1_start.setMinimumSize(QtCore.QSize(0, 0))
        self.label_T1_start.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_T1_start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T1_start.setObjectName("label_T1_start")
        self.layout_T1_start.addWidget(self.label_T1_start)
        self.layout_T1.addLayout(self.layout_T1_start)
        self.layout_T1_stop = QtWidgets.QVBoxLayout()
        self.layout_T1_stop.setObjectName("layout_T1_stop")
        self.param_T1_stop = ScientificSpinBox(self.tab_parameters)
        self.param_T1_stop.setMinimumSize(QtCore.QSize(80, 0))
        self.param_T1_stop.setMaximum(100.0)
        self.param_T1_stop.setObjectName("param_T1_stop")
        self.layout_T1_stop.addWidget(self.param_T1_stop)
        self.label_T1_stop = QtWidgets.QLabel(self.tab_parameters)
        self.label_T1_stop.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_T1_stop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T1_stop.setObjectName("label_T1_stop")
        self.layout_T1_stop.addWidget(self.label_T1_stop)
        self.layout_T1.addLayout(self.layout_T1_stop)
        self.layout_T1_points = QtWidgets.QVBoxLayout()
        self.layout_T1_points.setObjectName("layout_T1_points")
        self.param_T1_points = QtWidgets.QSpinBox(self.tab_parameters)
        self.param_T1_points.setMinimumSize(QtCore.QSize(80, 0))
        self.param_T1_points.setMaximum(1000)
        self.param_T1_points.setObjectName("param_T1_points")
        self.layout_T1_points.addWidget(self.param_T1_points)
        self.label_T1_points = QtWidgets.QLabel(self.tab_parameters)
        self.label_T1_points.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_T1_points.setAlignment(QtCore.Qt.AlignCenter)
        self.label_T1_points.setObjectName("label_T1_points")
        self.layout_T1_points.addWidget(self.label_T1_points)
        self.layout_T1.addLayout(self.layout_T1_points)
        self.layout_T1_LaserLength = QtWidgets.QVBoxLayout()
        self.layout_T1_LaserLength.setObjectName("layout_T1_LaserLength")
        self.param_T1_LaserLength = ScientificSpinBox(self.tab_parameters)
        self.param_T1_LaserLength.setMinimumSize(QtCore.QSize(80, 0))
        self.param_T1_LaserLength.setObjectName("param_T1_LaserLength")
        self.layout_T1_LaserLength.addWidget(self.param_T1_LaserLength)
        self.laserlengthLabel = QtWidgets.QLabel(self.tab_parameters)
        self.laserlengthLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.laserlengthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.laserlengthLabel.setObjectName("laserlengthLabel")
        self.layout_T1_LaserLength.addWidget(self.laserlengthLabel)
        self.layout_T1.addLayout(self.layout_T1_LaserLength)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_T1.addItem(spacerItem3)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.layout_T1)
        self.label_MWLaserON_name = QtWidgets.QLabel(self.tab_parameters)
        self.label_MWLaserON_name.setObjectName("label_MWLaserON_name")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_MWLaserON_name
        )
        self.layout_MWLaserON = QtWidgets.QHBoxLayout()
        self.layout_MWLaserON.setObjectName("layout_MWLaserON")
        self.layout_MWLaserON_select = QtWidgets.QVBoxLayout()
        self.layout_MWLaserON_select.setObjectName("layout_MWLaserON_select")
        self.button_MWLaserON_select = QtWidgets.QPushButton(self.tab_parameters)
        self.button_MWLaserON_select.setObjectName("button_MWLaserON_select")
        self.layout_MWLaserON_select.addWidget(self.button_MWLaserON_select)
        self.button_MWLaserON_remove = QtWidgets.QPushButton(self.tab_parameters)
        self.button_MWLaserON_remove.setObjectName("button_MWLaserON_remove")
        self.layout_MWLaserON_select.addWidget(self.button_MWLaserON_remove)
        self.layout_MWLaserON.addLayout(self.layout_MWLaserON_select)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.layout_MWLaserON.addItem(spacerItem4)
        self.formLayout.setLayout(
            1, QtWidgets.QFormLayout.FieldRole, self.layout_MWLaserON
        )
        self.verticalLayout_4.addLayout(self.formLayout)
        self.verticalLayout_4.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_parameters, "")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_plot)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_program = QtWidgets.QLabel(self.tab_plot)
        self.label_program.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_program.setObjectName("label_program")
        self.verticalLayout_5.addWidget(self.label_program)
        self.plot_program = PlotWidget(self.tab_plot)
        self.plot_program.setObjectName("plot_program")
        self.verticalLayout_5.addWidget(self.plot_program)
        self.tabWidget.addTab(self.tab_plot, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_channels.setText(_translate("MainWindow", "Channels"))
        self.label_channel_MW.setText(_translate("MainWindow", "MW"))
        self.label_channel_laser.setText(_translate("MainWindow", "Laser"))
        self.label_channel_counter.setText(_translate("MainWindow", "Counter"))
        self.label_general.setText(_translate("MainWindow", "General Settings"))
        self.label_general_MWamp.setText(_translate("MainWindow", "MW amplitude"))
        self.label_general_AOMdelay.setText(_translate("MainWindow", "AOM delay"))
        self.label_general_wait.setText(_translate("MainWindow", "Final wait"))
        self.label_general_bin.setText(_translate("MainWindow", "Binwidth"))
        # self.comboBox_list_sequence.setItemText(0, _translate("MainWindow", "sequence"))
        self.button_add_sequence.setText(_translate("MainWindow", "Add"))
        self.label_T1_name.setText(_translate("MainWindow", "T1"))
        self.button_T1_select.setText(_translate("MainWindow", "Select"))
        self.button_T1_remove.setText(_translate("MainWindow", "Remove"))
        self.label_T1_start.setText(_translate("MainWindow", "Start tau"))
        self.label_T1_stop.setText(_translate("MainWindow", "Stop tau"))
        self.label_T1_points.setText(_translate("MainWindow", "N points"))
        self.laserlengthLabel.setText(_translate("MainWindow", "Laser length"))
        self.label_MWLaserON_name.setText(_translate("MainWindow", "MW and Laser ON"))
        self.button_MWLaserON_select.setText(_translate("MainWindow", "Select"))
        self.button_MWLaserON_remove.setText(_translate("MainWindow", "Remove"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_parameters),
            _translate("MainWindow", "Parameters"),
        )
        self.label_program.setText(
            _translate("MainWindow", "Programmed Pulse Sequence")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_plot), _translate("MainWindow", "Sequence")
        )

    def add_sequence(self, name):
        """
        Add the sequence selcted with the combo box to the GUI and create all its parameter widgets.
        """
        ########################################
        # Parse the sequence specific parameters
        ########################################
        params_dict = {}
        for attr, attr_type in inspect.get_annotations(
            getattr(pymodaq_pulse_sequences, f"Sequence_{name}")
        ).items():
            if attr.startswith("gui_"):
                params_dict["_".join(map(str, attr.split("_")[1:]))] = attr_type

        ############################################################
        # Create the sequence widget and add them to the form layout
        ############################################################
        count = self.formLayout.rowCount()
        # Set the form label to the equence name
        self.__dict__[f"label_{name}_name"] = QtWidgets.QLabel(self.tab_parameters)
        self.__dict__[f"label_{name}_name"].setAlignment(QtCore.Qt.AlignCenter)
        # self.__dict__[f"label_{name}_name"].setObjectName(f"label_{name}_name")
        self.__dict__[f"label_{name}_name"].setText(name)
        self.formLayout.setWidget(
            count, QtWidgets.QFormLayout.LabelRole, self.__dict__[f"label_{name}_name"]
        )
        # Create the layout for thhe parameters widgets
        self.__dict__[f"layout_{name}"] = QtWidgets.QHBoxLayout()
        # self.__dict__[f"layout_{name}"].setObjectName(f"layout_{name}")
        self.__dict__[f"layout_{name}"].setSpacing(6)
        # Create the Select/Remove buttons
        self.__dict__[f"layout_{name}_select"] = QtWidgets.QVBoxLayout()
        # self.__dict__[f"layout_{name}_select"].setObjectName(f"layout_{name}_select")
        self.__dict__[f"button_{name}_select"] = QtWidgets.QPushButton(
            self.tab_parameters
        )
        self.__dict__[f"button_{name}_select"].setMaximumSize(
            QtCore.QSize(80, 16777215)
        )
        # self.__dict__[f"button_{name}_select"].setObjectName(f"button_{name}_select")
        self.__dict__[f"button_{name}_select"].setText("Select")
        self.__dict__[f"layout_{name}_select"].addWidget(
            self.__dict__[f"button_{name}_select"]
        )
        self.__dict__[f"button_{name}_remove"] = QtWidgets.QPushButton(
            self.tab_parameters
        )
        # self.__dict__[f"button_{name}_remove"].setObjectName(f"button_{name}_remove")
        self.__dict__[f"button_{name}_remove"].setText("Remove")
        self.__dict__[f"layout_{name}_select"].addWidget(
            self.__dict__[f"button_{name}_remove"]
        )
        self.__dict__[f"layout_{name}"].addLayout(
            self.__dict__[f"layout_{name}_select"]
        )
        # Create the widgets for the parameters
        for p, t in params_dict.items():
            # make the layout for the parameter widgets
            self.__dict__[f"layout_{name}_{p}"] = QtWidgets.QVBoxLayout()
            # self.__dict__[f"layout_{name}_{p}"].setObjectName(f"layout_{name}_{p}")
            # make the spinbox and label widgets
            if t == float:
                self.__dict__[f"param_{name}_{p}"] = ScientificSpinBox(
                    self.tab_parameters,
                    base_unit="ns",
                    allowed_units=["ns", "us", "ms"],
                )
            elif t == int:
                self.__dict__[f"param_{name}_{p}"] = QtWidgets.QSpinBox(
                    self.tab_parameters
                )
            else:
                raise TypeError(
                    f"Invalid parameter type: {t}. The parameter should be float or int."
                )
            self.__dict__[f"param_{name}_{p}"].setMinimumSize(QtCore.QSize(80, 0))
            # self.__dict__[f"param_{name}_{p}"].setObjectName(f"param_{name}_{p}")
            self.__dict__[f"layout_{name}_{p}"].addWidget(
                self.__dict__[f"param_{name}_{p}"]
            )
            self.__dict__[f"label_{name}_{p}"] = QtWidgets.QLabel(self.tab_parameters)
            self.__dict__[f"label_{name}_{p}"].setMinimumSize(QtCore.QSize(0, 0))
            self.__dict__[f"label_{name}_{p}"].setMaximumSize(
                QtCore.QSize(16777215, 15)
            )
            self.__dict__[f"label_{name}_{p}"].setAlignment(QtCore.Qt.AlignCenter)
            # self.__dict__[f"label_{name}_{p}"].setObjectName(f"label_{name}_{p}")
            self.__dict__[f"label_{name}_{p}"].setText(
                " ".join(map(str, p.split("_")))
            )  # we replace the _ with spaces for the parameter names in the gui
            self.__dict__[f"layout_{name}_{p}"].addWidget(
                self.__dict__[f"label_{name}_{p}"]
            )
            self.__dict__[f"layout_{name}"].addLayout(
                self.__dict__[f"layout_{name}_{p}"]
            )
        # add the spacer to keep thing on the left
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.__dict__[f"layout_{name}"].addItem(spacerItem)
        self.formLayout.setLayout(
            count, QtWidgets.QFormLayout.FieldRole, self.__dict__[f"layout_{name}"]
        )

        #######################################
        # Connect the Select and Remove buttons
        #######################################
        self.__dict__[f"button_{name}_select"].clicked.connect(
            lambda: setattr(self.selected_sequence, name)
        )
        self.__dict__[f"button_{name}_remove"].clicked.connect(
            lambda: self.remove_sequence(name)
        )

    def remove_sequence(self, name):
        seq_label = self.formLayout.labelForField(self.__dict__[f"layout_{name}"])
        if seq_label is not None:
            seq_label.deleteLater()
        deleteItems(self.__dict__[f"layout_{name}"])
        self.__dict__[f"layout_{name}"].deleteLater()


def deleteItems(layout):
    if layout is not None:
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget is not None:
                widget.deleteLater()
            else:
                deleteItems(item.layout())


from pyqtgraph import PlotWidget
from scientific_spinbox.widget import ScientificSpinBox


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
